---
- name: Ensure the application group exists
  group:
    name: "{{ nodejs_app_groupname }}"
    state: present

- name: Ensure the application user account exists
  user:
    name: "{{ nodejs_app_username }}"
    comment: "Node.js System Account"
    group: "{{ nodejs_app_groupname }}"
    shell: "{{ nodejs_app_user_shell }}"
    home: "{{ nodejs_app_home_dir }}"

- name: Clone application repository
  git:
    repo: "{{ nodejs_app_git_repo | mandatory }}"
    dest: "{{ nodejs_app_install_dir | mandatory }}"
    version: "{{ nodejs_app_git_branch | mandatory }}"
    depth: 1
  when: nodejs_app_git_clone

- name: Make sure the application install directory exists and is owned by the appropriate user
  file:
      path: "{{ nodejs_app_install_dir }}"
      owner: "{{ nodejs_app_dev_username if is_vagrant else nodejs_app_username }}"
      group: "{{ nodejs_app_dev_username if is_vagrant else nodejs_app_username }}"
      recurse: true
      state: directory
  when: not is_vagrant

- name: Run application related commands as the application user
  command: "{{ item }}"
  args:
    chdir: "{{ nodejs_app_install_dir }}"
  with_items: "{{ nodejs_app_commands }}"
  become: yes
  become_user: "{{ nodejs_app_dev_username if is_vagrant else nodejs_app_username }}"
  when: nodejs_app_commands
