---
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - always

- name: Include Install-related tasks
  import_tasks: install.yml
  tags:
    - install

- name: Include Configure-related tasks
  import_tasks: configure.yml
  tags:
    - configure

- name: Include Deploy-related tasks
  import_tasks: deploy.yml
  tags:
    - deploy

- name: Include Test-related tasks
  import_tasks: test.yml
  when: >
    (nodejs_app_host_address) and (nodejs_app_tcp_port) and (nodejs_app_test_http_endpoint) and
    (nodejs_app_test_http_status_code) and (nodejs_app_test_string)
  tags:
    - test
